name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-19"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "67cf4ff4-f0bf-4a2f-80c8-99ef3857b4e0"
